spring:
  application:
    name: TPO10
  
  datasource:
    url: jdbc:h2:file:./db/links
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  sql:
    init:
      mode: embedded
      

