spring:
  banner:
    location: logo-app
  application:
    name: TPO3
  profiles:
    active: uppercase
  h2:
    console:
      path: /h2
  datasource:
    url: jdbc:h2:file:./db/dictionary
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
