INSERT INTO publisher (name) VALUES
('Penguin Random House'),
('HarperCollins'),
('Simon & Schuster'),
('Macmillan'),
('Hachette Book Group'),
('Pearson'),
('McGraw-Hill Education'),
('Oxford University Press'),
('Wiley'),
('Springer Nature'),
('Elsevier'),
('John Wiley & Sons'),
('Routledge'),
('Kogan Page'),
('Cambridge University Press'),
('Taylor & Francis'),
('SAGE Publications'),
('Bloomsbury Publishing'),
('MIT Press'),
('University of Chicago Press');
