INSERT INTO ENTRY(ID, ENGLISH, POLISH, GERMAN) VALUES (1,'Apple', 'Jabłko', 'Apfel' );
INSERT INTO ENTRY(ID, ENGLISH, POLISH, GERMAN) VALUES (2, 'House', 'Dom', 'Haus');
INSERT INTO ENTRY(ID, ENGLISH, POLISH, GERMAN) VALUES (3, 'Apple', 'Jabłko', 'Apfel' );
INSERT INTO ENTRY(ID, ENGLISH, POLISH, GERMAN) VALUES (4, 'Dog', 'Pies', 'Hund');
INSERT INTO ENTRY(ID, ENGLISH, POLISH, GERMAN) VALUES (5, 'Water', 'Woda', 'Wasser');
INSERT INTO ENTRY(ID, ENGLISH, POLISH, GERMAN) VALUES (6,'Sun', 'Słońce', 'Sonne' );
INSERT INTO ENTRY(ID, ENGLISH, POLISH, GERMAN) VALUES (7, 'Book', 'Książka', 'Buch');
