INSERT INTO articles (title, author_id, blog_id) VALUES
('Getting Started with Spring Boot', 1, 17),
('Best Italian Pasta Recipes', 2, 2),
('Exploring the Hidden Beaches of Thailand', 3, 3),
('5 Effective Cardio Workouts', 4, 4),
('Review: The Midnight Library', 5, 5),
('Mastering Portrait Photography', 6, 6),
('Investing in ETFs for Beginners', 7, 7),
('Top 10 Sci-Fi Films of 2024', 8, 8),
('Build Your Own Bookshelf', 9, 9),
('Growing Vegetables in Small Spaces', 10, 10),
('Summer Fashion Essentials', 11, 11),
('Analysis of Premier League Season', 12, 12),
('Understanding Quantum Computing', 13, 13),
('Album Review: Latest Indie Releases', 14, 14),
('Benefits of Meditation', 15, 15),
('Contemporary Art Movements', 16, 16),
('Microservices Architecture Patterns', 17, 17),
('Caring for Senior Cats', 18, 18),
('Positive Discipline Techniques', 19, 19),
('Negotiating Your Salary', 20, 20),
('Advanced React Hooks', 1, 17),
('Authentic Mexican Cuisine', 2, 2),
('Mountain Hiking Guide', 3, 3),
('Strength Training for Beginners', 4, 4),
('Best Fantasy Books of 2024', 5, 5),
('Landscape Photography Tips', 6, 6),
('Retirement Planning Essentials', 7, 7),
('Classic Film Recommendations', 8, 8),
('DIY Home Renovation Ideas', 9, 9),
('Organic Pest Control Methods', 10, 10);
