INSERT INTO blogs (name, manager_id) VALUES
('Tech Insights', 1),
('Cooking Adventures', 2),
('Travel Diaries', 3),
('Fitness Journey', 4),
('Book Reviews', 5),
('Photography Tips', 6),
('Personal Finance', 7),
('Movie Critiques', 8),
('DIY Projects', 9),
('Gardening Guide', 10),
('Fashion Trends', 11),
('Sports Analytics', 12),
('Science Explained', 13),
('Music Reviews', 14),
('Health & Wellness', 15),
('Art Gallery', 16),
('Software Development', 17),
('Pet Care', 18),
('Parenting Tips', 19),
('Career Advice', 20);
